# Generated by Django 5.2.5 on 2025-08-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('Food', 'Food & Dining'), ('Shopping', 'Shopping'), ('Housing', 'Housing & Rent'), ('Transportation', 'Transportation'), ('Entertainment', 'Entertainment'), ('Utilities', 'Utilities'), ('Healthcare', 'Healthcare'), ('Salary', 'Salary'), ('Investment', 'Investment'), ('Other', 'Other')], max_length=32)),
                ('type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
